/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    companies: Company;
    users: User;
    media: Media;
    products: Product;
    'product-variants': ProductVariant;
    'price-lists': PriceList;
    quotes: Quote;
    orders: Order;
    carts: Cart;
    'cart-bulk-adds': CartBulkAdd;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-variants': ProductVariantsSelect<false> | ProductVariantsSelect<true>;
    'price-lists': PriceListsSelect<false> | PriceListsSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    'cart-bulk-adds': CartBulkAddsSelect<false> | CartBulkAddsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: number;
  name: string;
  /**
   * Optional SAP S/4 customer number for a future MuleSoft integration.
   */
  sapCustomerNumber?: string | null;
  /**
   * When false, vendor users for this company cannot sign in.
   */
  accountApproved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'sales' | 'vendor-buyer';
  company?: (number | null) | Company;
  /**
   * Vendor buyers must be approved before they can sign in.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * URL-friendly identifier for PDP routes.
   */
  slug: string;
  /**
   * Base model number (PLP MODEL line).
   */
  modelNumber?: string | null;
  /**
   * Design collection (e.g. Townsend, Champion).
   */
  productCollection: string;
  /**
   * Category for PLP facets and copy.
   */
  catalogCategory?: ('bathroom-faucet' | 'kitchen-faucet' | 'toilet') | null;
  /**
   * Hide from vendor PLP and catalog search.
   */
  catalogHidden: boolean;
  breadcrumbs?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  description?: string | null;
  /**
   * Up to 3 short bullets for buy box.
   */
  shortBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Full feature list (Product Overview).
   */
  featureBullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Grouped specification tables (PDP Specifications).
   */
  specGroups?:
    | {
        groupName: string;
        rows?:
          | {
              label: string;
              value: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy flat specs (optional).
   */
  specsTable?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Product-level PDFs and external downloads.
   */
  documents?:
    | {
        docType: 'spec-sheet' | 'install-instructions' | 'parts-diagram' | 'cad-2d' | 'revit';
        /**
         * PDF upload (spec, install, parts diagram).
         */
        file?: (number | null) | Media;
        /**
         * External URL (CAD, Revit, etc.).
         */
        externalUrl?: string | null;
        displayName?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * YouTube video id for Installation / overview embed.
   */
  youtubeVideoId?: string | null;
  /**
   * PLP facet values derived from specs.
   */
  facetMeta?: {
    handleType?: string | null;
    holesRequired?: string | null;
    ada?: string | null;
    bowlShape?: string | null;
    flushTechnology?: string | null;
    gpf?: string | null;
  };
  /**
   * PLP thumbnail / default PDP hero when no finish selected.
   */
  primaryImage?: (number | null) | Media;
  /**
   * Product-level gallery (lifestyle / alternate angles).
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
  id: number;
  sku: string;
  name: string;
  product: number | Product;
  /**
   * Finish name shown in the PDP finish selector (e.g. Chrome).
   */
  finish: string;
  /**
   * List / compare-at price (struck through on PDP).
   */
  msrp?: number | null;
  upc?: string | null;
  inStock?: boolean | null;
  discontinued?: boolean | null;
  /**
   * Minimum order quantity (MOQ) for this SKU.
   */
  moq: number;
  /**
   * Order increment / case pack size.
   */
  orderMultiple: number;
  specs?: {
    flowRateGpm?: number | null;
    spoutHeightIn?: number | null;
    material?: string | null;
    /**
     * e.g. WaterSense, ADA
     */
    certifications?: string | null;
  };
  /**
   * Finish-specific images for gallery / selector.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Legacy — prefer product documents[].
   */
  specPdf?: (number | null) | Media;
  /**
   * Legacy — prefer product documents[].
   */
  installPdf?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists".
 */
export interface PriceList {
  id: number;
  name: string;
  kind: 'standard' | 'company';
  company?: (number | null) | Company;
  validFrom?: string | null;
  validTo?: string | null;
  lines: {
    variant: number | ProductVariant;
    unitPrice: number;
    currency?: string | null;
    quantityBreaks?:
      | {
          minQuantity: number;
          unitPrice: number;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  quoteNumber: string;
  company: number | Company;
  status: 'draft' | 'sent' | 'accepted' | 'expired' | 'cancelled';
  expiresAt: string;
  lines: {
    sku: string;
    variant?: (number | null) | ProductVariant;
    quantity: number;
    unitPrice: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Generated on submit if empty.
   */
  orderNumber?: string | null;
  company: number | Company;
  status: 'draft' | 'submitted' | 'confirmed' | 'shipped' | 'cancelled';
  poNumber?: string | null;
  quote?: (number | null) | Quote;
  /**
   * Client-supplied key to dedupe submit requests.
   */
  idempotencyKey?: string | null;
  shipTo: {
    name: string;
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
  };
  lines: {
    sku: string;
    variant?: (number | null) | ProductVariant;
    quantity: number;
    unitPrice: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user: number | User;
  company: number | Company;
  lines?:
    | {
        sku: string;
        variant?: (number | null) | ProductVariant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-bulk-adds".
 */
export interface CartBulkAdd {
  id: number;
  user: number | User;
  company: number | Company;
  idempotencyKey: string;
  addedSkus:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'companies';
        value: number | Company;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-variants';
        value: number | ProductVariant;
      } | null)
    | ({
        relationTo: 'price-lists';
        value: number | PriceList;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'cart-bulk-adds';
        value: number | CartBulkAdd;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  sapCustomerNumber?: T;
  accountApproved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  modelNumber?: T;
  productCollection?: T;
  catalogCategory?: T;
  catalogHidden?: T;
  breadcrumbs?:
    | T
    | {
        label?: T;
        id?: T;
      };
  description?: T;
  shortBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featureBullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specGroups?:
    | T
    | {
        groupName?: T;
        rows?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  specsTable?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        docType?: T;
        file?: T;
        externalUrl?: T;
        displayName?: T;
        id?: T;
      };
  youtubeVideoId?: T;
  facetMeta?:
    | T
    | {
        handleType?: T;
        holesRequired?: T;
        ada?: T;
        bowlShape?: T;
        flushTechnology?: T;
        gpf?: T;
      };
  primaryImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants_select".
 */
export interface ProductVariantsSelect<T extends boolean = true> {
  sku?: T;
  name?: T;
  product?: T;
  finish?: T;
  msrp?: T;
  upc?: T;
  inStock?: T;
  discontinued?: T;
  moq?: T;
  orderMultiple?: T;
  specs?:
    | T
    | {
        flowRateGpm?: T;
        spoutHeightIn?: T;
        material?: T;
        certifications?: T;
      };
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  specPdf?: T;
  installPdf?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-lists_select".
 */
export interface PriceListsSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  company?: T;
  validFrom?: T;
  validTo?: T;
  lines?:
    | T
    | {
        variant?: T;
        unitPrice?: T;
        currency?: T;
        quantityBreaks?:
          | T
          | {
              minQuantity?: T;
              unitPrice?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  company?: T;
  status?: T;
  expiresAt?: T;
  lines?:
    | T
    | {
        sku?: T;
        variant?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  company?: T;
  status?: T;
  poNumber?: T;
  quote?: T;
  idempotencyKey?: T;
  shipTo?:
    | T
    | {
        name?: T;
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  lines?:
    | T
    | {
        sku?: T;
        variant?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  company?: T;
  lines?:
    | T
    | {
        sku?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cart-bulk-adds_select".
 */
export interface CartBulkAddsSelect<T extends boolean = true> {
  user?: T;
  company?: T;
  idempotencyKey?: T;
  addedSkus?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}